### ISSUE TITLE
Interest in publishing to NuGet?

### ISSUE THREAD

**Issue by Scrambles56** [AlexeyRaga/kafkaflow-contrib#1]
Having these packages available on nuget would make them much easier to be used. If you're interested, I can look at what would be needed to set up the CI pipeline to do so. 

From a cursory glance, what I have found is the following:
- KafkaFlow nuget prefix is reserved. Project's would need to be renamed, e.g `ARaga.KafkaFlow.Contrib.*`
- An owner nuget account would need to be created, and the api token would need to be added as an actions secret.

**Comment by AlexeyRaga** [comment]
I have some packages on Nuget, so I should gave an account... I just thought that it'd be moved under EP eventually :)
Can think about it though.

**Comment by AlexeyRaga** [comment]
Packages are published:
```
Contrib.KafkaFlow.Outbox
Contrib.KafkaFlow.Outbox.Postgres
Contrib.KafkaFlow.ProcessManagers
Contrib.KafkaFlow.ProcessManagers.Postgres
```
